from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, model_validator


class PurchaseCategoryBase(BaseModel):
    name: str
    color: Optional[str] = None


class PurchaseCategoryCreate(PurchaseCategoryBase):
    pass


class PurchaseCategoryUpdate(BaseModel):
    name: Optional[str] = None
    color: Optional[str] = None


class PurchaseCategoryRead(PurchaseCategoryBase):
    id: str
    created_by_ai: bool = False
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PurchaseCartItemBase(BaseModel):
    product_name: str
    price: float
    quantity: int = 1
    category_id: Optional[str] = None


class PurchaseCartItemCreate(PurchaseCartItemBase):
    # Optional id generated by the client. The frontend queues cart changes
    # made without signal and retries them later, so sending the same id twice
    # must not add the product twice (see add_cart_item).
    id: Optional[UUID] = None
    # Product picked from the suggestions; without it the product is found
    # (or created) from product_name.
    product_id: Optional[str] = None


class PurchaseCartItemUpdate(BaseModel):
    product_name: Optional[str] = None
    price: Optional[float] = None
    quantity: Optional[int] = None
    # Sending null explicitly removes the item's own category (it goes back
    # to its product's).
    category_id: Optional[str] = None


class PurchaseCartItemRead(PurchaseCartItemBase):
    id: str
    cart_id: str
    product_id: Optional[str] = None
    category_name: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PurchaseProductUpdate(BaseModel):
    name: Optional[str] = None
    # null removes the category.
    category_id: Optional[str] = None
    size_value: Optional[float] = None
    size_unit: Optional[str] = None


class PurchaseProductMerge(BaseModel):
    # The product that stays; the one in the URL is merged into it.
    into_product_id: str


class PurchaseProductRead(BaseModel):
    id: str
    name: str
    category_id: Optional[str] = None
    category_name: Optional[str] = None
    category_source: Optional[str] = None
    size_value: Optional[float] = None
    size_unit: Optional[str] = None
    times_bought: int = 0
    total_spent: float = 0
    last_price: Optional[float] = None
    min_price: Optional[float] = None
    max_price: Optional[float] = None
    last_store: Optional[str] = None
    last_bought_at: Optional[datetime] = None
    aliases: List[str] = []
    created_at: datetime


class PurchaseProductLinkResult(BaseModel):
    linked_items: int
    created_products: int


class PurchaseStoreBase(BaseModel):
    name: str


class PurchaseStoreCreate(PurchaseStoreBase):
    pass


class PurchaseStoreUpdate(BaseModel):
    name: Optional[str] = None


class PurchaseStoreRead(PurchaseStoreBase):
    id: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PurchaseCartCreate(BaseModel):
    # Either a store from the user's list, or a name: an unknown name is added
    # to the list (see create_cart).
    store_id: Optional[str] = None
    store_name: Optional[str] = None

    @model_validator(mode="after")
    def check_store(self):
        if not self.store_id and not (self.store_name and self.store_name.strip()):
            raise ValueError("store_id or store_name is required")
        return self


class PurchaseCartUpdate(BaseModel):
    store_name: Optional[str] = None
    is_active: Optional[bool] = None


class PurchaseCartRead(BaseModel):
    id: str
    store_id: Optional[str] = None
    store_name: Optional[str] = None
    user_id: str
    is_active: bool
    total: float
    created_at: datetime
    updated_at: datetime
    completed_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class PurchaseCartWithItems(PurchaseCartRead):
    items: List[PurchaseCartItemRead] = []


class PurchaseListItemBase(BaseModel):
    product_name: str
    quantity: Optional[int] = None


class PurchaseListItemCreate(PurchaseListItemBase):
    pass


class PurchaseListItemUpdate(BaseModel):
    product_name: Optional[str] = None
    quantity: Optional[int] = None
    is_checked: Optional[bool] = None


class PurchaseListItemRead(PurchaseListItemBase):
    id: str
    list_id: str
    is_checked: bool
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PurchaseListBase(BaseModel):
    name: str


class PurchaseListCreate(PurchaseListBase):
    pass


class PurchaseListUpdate(BaseModel):
    name: Optional[str] = None


class PurchaseListRead(PurchaseListBase):
    id: str
    user_id: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PurchaseListWithItems(PurchaseListRead):
    items: List[PurchaseListItemRead] = []
